### ISSUE TITLE
Would you mind if I also work on this?

### ISSUE THREAD

**Issue by joshiayush** [anthonygraca/leetcode#1]
@anthonygraca As the title suggest I'm also prepping for interviews I've started doing __leetcode__ but there's no option there to show the quality of code you've written to solve the problem. I would also like to contribute here... solve __leetcode__ problems here if you don't mind accepting PRs from my side.

**Comment by anthonygraca** [comment]
Sure. Submit a PR and if it looks good, I'll approve it. I would appreciate it if you followed the same format w/ the table of contents in the readme and you made all the code written easy to compile and testable
